---
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: inline
---

```{r}
library(ggplot2)
library(dplyr)
library(crayon)
```

```{r}
df <- read.csv("jobs_in_data.csv")

ejeX <- aes(x=job_category, fill=work_setting)

ggplot(df, ejeX ) + 
  geom_bar() +
  theme(axis.text.x = element_text
        (size = 9, 
          color = "blue",
          face = "italic", 
          angle = 320,
          vjust = 0.9,
          hjust = -0.009)
        ) + 
  labs(x = "Job Category",
       y = "Count",
       title = "Data Science: Count by job category",
       fill = "work setting"
       ) +
  theme(legend.text = element_text
        (
          color = "red",
          face = "bold"),
        axis.title = element_text(size = 12),
        legend.byrow = FALSE
        )
```

```{r}
ratio.display <- 4/3
par(mar=c(5,4,2,6))

boxPlot <- ggplot(df, aes(x = job_category, y = salary/1000,xlab = "", ylab = "")) +
  geom_boxplot() +
  theme(axis.text.x = element_text
        (size = 9, 
          color = "blue",
          face = "italic", 
          angle = 320,
          vjust = 0.9,
          hjust = -0.009)
        ) +
  labs(x = "Job Category", 
       y = "Anual Salary/1000",
       title = "Data Science: Salary distribution by job category"
       )
boxPlot + coord_fixed(ratio = (6/11)/41)

```

```{r}
ggplot(df, aes(x = experience_level, y = salary)) +
  geom_violin()
```
